; 手势识别项目
; 需要额外库：SparkFun APDS-9960
[platformio]
default_envs = esp32dev

[env:esp32dev]
extends = env:esp32dev
build_src_filter = +<*>
lib_deps =
    ${env:esp32dev.lib_deps}
    sparkfun/SparkFun APDS9960 RGB and Gesture Sensor@^1.4.3
build_flags =
    -DBOARD_NAME="GestureControl"
