; 手势识别项目
[platformio]
default_envs = esp32dev

[env:esp32dev]
platform  = espressif32@6.7.0
board     = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.9
    sparkfun/SparkFun APDS9960 RGB and Gesture Sensor@^1.4.3

build_src_filter = +<*>
build_flags =
    -DBOARD_NAME="GestureControl"
