; 433MHz RF 智能网关
[platformio]
default_envs = esp32dev

[env:esp32dev]
platform  = espressif32@6.7.0
board     = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.9
    sui77/rc-switch@^2.6.4
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.2.1

build_src_filter = +<*>
build_flags =
    -DBOARD_NAME="RFGateway"
    -DMQTT_MAX_PACKET_SIZE=1024
