; 433MHz RF 智能网关
; 关键库：rc-switch（支持市售大多数433MHz设备）
[platformio]
default_envs = esp32dev

[env:esp32dev]
extends = env:esp32dev
build_src_filter = +<*>
lib_deps =
    ${env:esp32dev.lib_deps}
    sui77/rc-switch@^2.6.4
    knolleary/PubSubClient@^2.8
build_flags =
    -DBOARD_NAME="RFGateway"
    -DMQTT_MAX_PACKET_SIZE=1024
