; AI 摄像头项目（ESP32-CAM AI Thinker）
; 注意：烧录时 IO0 必须接 GND！
[platformio]
default_envs = esp32cam

[env:esp32cam]
extends = env:esp32cam
build_src_filter = +<*>
; 摄像头需要较大分区，使用带 OTA 的分区表
board_build.partitions = huge_app.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=0
