; IR 红外万能遥控项目
[platformio]
default_envs = esp32dev

[env:esp32dev]
platform  = espressif32@6.7.0
board     = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.9
    crankyoldgit/IRremoteESP8266@^2.8.6
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.2.1

build_src_filter = +<*>
build_flags =
    -DBOARD_NAME="IRBlaster"
    -DMQTT_MAX_PACKET_SIZE=512
