; IR 红外万能遥控项目
; 关键库：IRremoteESP8266（支持100+空调品牌协议）
[platformio]
default_envs = esp32dev

[env:esp32dev]
extends = env:esp32dev
build_src_filter = +<*>
lib_deps =
    ${env:esp32dev.lib_deps}
    crankyoldgit/IRremoteESP8266@^2.8.6
    knolleary/PubSubClient@^2.8
build_flags =
    -DBOARD_NAME="IRBlaster"
    -DMQTT_MAX_PACKET_SIZE=512
